dependencies:
  collection: ^1.15.0-nullsafety.4
name: ghostcoder
description: writes code for you
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  dart_style: ^2.0.0
  pedantic: ^1.11.0
  recase: ^4.0.0-nullsafety.0
